[general]
tabs = [
    "initialization",
    "losweep",
    "data",
    # "telescope",
    "imaging",
]
active_tab = "initialization"

[telescope]
controller.class = "TelescopeMotorController"
controller.path = "./telescope.py"
azimuth_jog_voltage = 5
zenith_jog_voltage = 1

[defaults]
    [defaults.losweep]
    global_shift = 0.0
    df = 1.0
    deltaf = 100.0
    flagging_threshold = 3.0
    file_suffix = "none"
    second_sweep.df = 1.0

    [defaults.data_streaming]
    use_default_filename = true
    directory = "/data/"

    [defaults.rfsoc]
    bitstream = "/home/xilinx/dualchan_v2.bit"

    [defaults.channel]
    tone_list = "/home/nia/Documents/rfsoc-interface/Default_tone_list.npy"
    # tone_powers = "/home/onrkids/readout/host/params/Device_aSi1_Channel2_20220222_300K_200mK_max_readout_power.npy"
    # chanmask = "/home/onrkids/readout/host/params/chanmask_rfsoc2.npy"
    dsp = {lo_freq = 400e6, n_averages = 524288}
    rfin = 0.0
    rfout = 0.0

# [[rfsocs]]
# name = "RFSOC1"
# redis = {ip = "fe80::8472:ce87:2997:72ca", port = 6379}
# ethernet = {sourceip = "192.168.3.41", destip = "192.168.3.40", destmac = "681CA2123652", port = 4096}
# chanmask = "/home/onrkids/readout/host/params/chanmask_rfsoc1.npy"
# rfin = 5.0

# [[rfsocs]]
# name = "devrfsoc"
# redis = {ip = "192.168.2.25", port = 6379}
# rfin = 10.0
# rfout = 20.0
# dsp.lo_freq = 750e6
# lo_comport_a = "/dev/asu_if_synth"
# tone_list = "/home/shd/github/asureadout_singlechan/rfsoc-interface/default_tonelist.npy"
# [rfsocs.ethernet]
# sourceip_a = '192.168.3.41'
# sourceip_b = '192.168.4.4'
# destip_a = '192.168.3.40'
# destip_b = '192.168.4.40'
# destmac_a = 'FC5CEEB8C46C'
# destmac_b = '681CA2123652'
# port_a = 4096
# port_b = 4096

[[rfsocs]]
name = "devrfsoc"
redis = {ip = "192.168.1.10", port = 6379}
atten_comport = '/dev/IF2Attenuators'
[rfsocs.channel1]
lo_comport = '/dev/IF2System1LO'
sourceip = '192.168.3.40'
destip = '192.168.3.41'
destmac = '98B78520C5C0'
port = 4096
[rfsocs.channel2]
lo_comport = '/dev/IF2System2LO'
sourceip = '192.168.4.4'
destip = '192.168.4.40'
destmac = '681CA2123652'
port = 4096