[loggers]
keys=root,telescopeControl

[handlers]
keys=consoleHandler,fileHandler,telescopeFileHandler

[formatters]
keys=consoleFormatter,fileFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler,fileHandler

[logger_telescopeControl]
level=DEBUG
handlers=telescopeFileHandler,consoleHandler

[handler_consoleHandler]
class=StreamHandler
level=WARNING
formatter=consoleFormatter
args=(sys.stdout,)

[formatter_consoleFormatter]
class=rfsocinterface.logging_utils.CustomConsoleFormatter

[handler_fileHandler]
class=handlers.RotatingFileHandler
level=DEBUG
formatter=fileFormatter
args=(os.path.expanduser('~') + '/.rfsocinterface/rfsocinterface.log', 'a', 10485760, 5)

[handler_telescopeFileHandler]
class=handlers.RotatingFileHandler
level=DEBUG
formatter=fileFormatter
args=(os.path.expanduser('~') + '/.rfsocinterface/telescope.log', 'a', 10485760, 5)

[formatter_fileFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)
